/**
 * Industry-specific keyword dictionaries for service keyword matching.
 * Keys match the industry values stored on prospects.
 */
export const INDUSTRY_KEYWORDS: Record<string, string[]> = {
  roofing: [
    "roof repair",
    "tile replacement",
    "guttering",
    "flat roof",
    "lead work",
    "fascia",
    "soffit",
    "ridge tile",
    "chimney",
    "velux",
    "felt roof",
    "emergency roof",
    "new roof",
    "roof replacement",
    "roof inspection",
  ],
  plumbing: [
    "boiler repair",
    "boiler installation",
    "central heating",
    "radiator",
    "leak repair",
    "drain unblocking",
    "bathroom fitting",
    "shower installation",
    "tap repair",
    "pipe repair",
    "emergency plumber",
    "gas safe",
    "hot water cylinder",
    "water softener",
  ],
  electrical: [
    "rewiring",
    "fuse box",
    "consumer unit",
    "electrical installation",
    "socket installation",
    "lighting installation",
    "PAT testing",
    "electrical inspection",
    "EV charger",
    "solar panel",
    "smart home",
    "EICR",
    "emergency electrician",
  ],
  landscaping: [
    "garden design",
    "lawn care",
    "decking",
    "patio installation",
    "hedge trimming",
    "tree surgery",
    "turf laying",
    "planting",
    "irrigation",
    "fencing",
    "garden clearance",
    "raised beds",
    "artificial grass",
    "block paving",
  ],
  cleaning: [
    "carpet cleaning",
    "end of tenancy",
    "deep cleaning",
    "oven cleaning",
    "window cleaning",
    "pressure washing",
    "office cleaning",
    "domestic cleaning",
    "move in clean",
    "after builders clean",
    "upholstery cleaning",
    "gutter cleaning",
  ],
  painting: [
    "interior painting",
    "exterior painting",
    "decorating",
    "wallpapering",
    "wood staining",
    "spray painting",
    "commercial painting",
    "residential painting",
    "render painting",
    "masonry paint",
    "sanding",
    "colour consultation",
  ],
  construction: [
    "extension",
    "loft conversion",
    "new build",
    "groundwork",
    "brickwork",
    "blockwork",
    "plastering",
    "carpentry",
    "joinery",
    "steel frame",
    "underpinning",
    "demolition",
    "project management",
    "building regulations",
  ],
  hvac: [
    "air conditioning",
    "HVAC installation",
    "heat pump",
    "ventilation",
    "air handling unit",
    "ductwork",
    "refrigeration",
    "cooling system",
    "heating system",
    "HVAC maintenance",
    "thermostat",
    "split system",
    "commercial HVAC",
  ],
  pest_control: [
    "rat removal",
    "mouse removal",
    "ant treatment",
    "wasp nest removal",
    "bed bug treatment",
    "cockroach control",
    "flea treatment",
    "squirrel removal",
    "bird proofing",
    "pest inspection",
    "fumigation",
    "rodent control",
  ],
  locksmith: [
    "lock replacement",
    "lock repair",
    "emergency locksmith",
    "key cutting",
    "safe opening",
    "door entry system",
    "lock upgrade",
    "burglary repair",
    "UPVC lock",
    "deadlock fitting",
    "security assessment",
    "master key system",
  ],
};
